import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
// import AauthThemeProvider from "@/provider/AuthThemeProvider copy";
import { AuthThemeProvider } from "@/provider/AuthThemeProvider";
import RootClientProvider from "@/provider/QueryClientProvider";
import { Toaster } from "@/components/ui/toaster"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center w-screen h-screen`}
      >
       

          <RootClientProvider>
            <AuthThemeProvider>
              {children}
              <Toaster />
            </AuthThemeProvider>
          </RootClientProvider>


      </body>

    </html>
  );
}


