export const facultyList = [
    {
        department: "Computer Science and Engineering",
        contactPersons: [
            {
                position: "Director General",
                name: "Dr. Biswajit Sahoo",
                email: "director.csit@kiit.ac.in",
                contact: "9437229507",
            },
            {
                position: "Dean, Research",
                name: "Dr. Hrudaya Kumar Tripathy",
                email: "dean_research.cse@kiit.ac.in",
                contact: "9437432185",
            },
            {
                position: "Dean, Academics (CS)",
                name: "Dr. Bhabani Sankar Prasad Mishra",
                email: "dean.cs@kiit.ac.in",
                contact: "9438037401",
            },
            {
                position: "Dean, Academics (IT)",
                name: "Dr. Arup Abhinna Acharya",
                email: "dean.it@kiit.ac.in",
                contact: "9861058079",
            },
            {
                position: "Dean, Academics (CC & CSM)",
                name: "Dr. Amulya Ratna Swain",
                email: "dean.ccm@kiit.ac.in",
                contact: "9439627127",
            },
            {
                position: "Associate Dean",
                name: "Dr. Ajay Kumar Jena",
                email: "ajay.jenafcs@kiit.ac.in",
                contact: "9437232068",
            },
            {
                position: "Dy. Controller of Examination",
                name: "Dr. Anuja Kumar Acharya",
                email: "dycoe.csit@kiit.ac.in",
                contact: "9438520431",
            },
            {
                position: "Asst. CoE-1",
                name: "Dr. Manas Ranjan Lenka",
                email: "acoe.cese@kiit.ac.in",
                contact: "9861077824",
            },
            {
                position: "Asst. CoE-2",
                name: "Mr. Sujoy Datta",
                email: "acoe.csit@kiit.ac.in",
                contact: "8093713885",
            },
            {
                position: "Asst. CoE-3",
                name: "Dr. Subhasis Dash",
                email: "fic.examcell.cse@kiit.ac.in",
                contact: "9437800206",
            },
            {
                position: "Asst. CoE-4",
                name: "Mr. Lalit Kumar Vashishtha",
                email: "fic.examcell.cse@kiit.ac.in",
                contact: "9668224395",
            },
            {
                position: "Associate Dean (T&P)",
                name: "Dr. Kumar Devadutta",
                email: "tnp.scs@kiit.ac.in",
                contact: "9437072128",
            },
            {
                position: "Sr. Administrative Officer",
                name: "Mr. Kshirod Kumar Nayak",
                email: "kshirod.nayak@kiit.ac.in",
                contact: "8223004014",
            },
            {
                position: "Faculty-In-Charges (Alumni Relation)",
                name: "Dr. Satarupa Mohanty",
                email: "satarupafcs@kiit.ac.in",
                contact: "9124941515",
            },
            {
                position: "Faculty-In-Charges (Alumni Relation)",
                name: "Dr. Namita Panda",
                email: "npandafcs@kiit.ac.in",
                contact: "9437444205",
            },
            {
                position: "Faculty-In-Charges (Alumni Relation)",
                name: "Ms. Shilpa Das",
                email: "shilpa.dasfcs@kiit.ac.in",
                contact: "7008810670",
            },
            {
                position: "Laboratory Governance",
                name: "Dr. Himansu Das",
                email: "himanshufcs@kiit.ac.in",
                contact: "9861335143",
            },
            {
                position: "Laboratory Governance",
                name: "Mrs. Suchismita Das",
                email: "suchismita.dasfcs@kiit.ac.in",
                contact: "8763977944",
            },
            {
                position: "Library Enrichment",
                name: "Ms. Aradhana Behura",
                email: "aradhana.behurafcs@kiit.ac.in",
                contact: "7787821733",
            },
            {
                position: "Quality Assurance",
                name: "Dr. Mohit Ranjan Panda",
                email: "qacell.cse@kiit.ac.in",
                contact: "9777999330",
            },
            {
                position: "Quality Assurance",
                name: "Dr. Adyasha Dash",
                email: "qacell.cse@kiit.ac.in",
                contact: "7077694248",
            },
            {
                position: "Quality Assurance",
                name: "Dr. Pratyusa Mukherjee",
                email: "qacell.cse@kiit.ac.in",
                contact: "9861937376",
            },
            {
                position: "Website & Social Media Management",
                name: "Ms. Santwana Sagnika",
                email: "webmaster.sce@kiit.ac.in",
                contact: "8093945565",
            },
            {
                position: "Website & Social Media Management",
                name: "Dr. Rabi Shaw",
                email: "webmaster.sce@kiit.ac.in",
                contact: "9007960872",
            },
            {
                position: "Student Affairs",
                name: "Dr. Manjusha Pandey",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "8763999448",
            },
            {
                position: "Student Affairs",
                name: "Dr. Leena Das",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "7750827038",
            },
            {
                position: "Student Affairs",
                name: "Ms. Roshni Pradhan",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "9439659354",
            },
            {
                position: "Student Affairs",
                name: "Mr. Sankalp Nayak",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "9853261679",
            },
            {
                position: "Student Affairs",
                name: "Mr. Ajit Kumar Pasayat",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "9040570908",
            },
            {
                position: "Student Affairs",
                name: "Ms. Mandakini Priyadarshani Behera",
                email: "ficstudentactivity.cse@kiit.ac.in",
                contact: "8917364496",
            },
            {
                position: "Student Affairs (NCC & NSS)",
                name: "Mr. R. N. Ramakanta Parida",
                email: "nss.sce@kiit.ac.in",
                contact: "7978036775",
            },
            {
                position: "Student Affairs (NCC & NSS)",
                name: "Dr. Minakhi Rout",
                email: "nss.sce@kiit.ac.in",
                contact: "9861108580",
            },
            {
                position: "Student Affairs (NCC & NSS)",
                name: "Mrs. Subhashree Darshana",
                email: "nss.sce@kiit.ac.in",
                contact: "7008097297",
            },
            {
                position: "International Student Affairs (Academics)",
                name: "Dr. Rajat Kumar Behera",
                email: "rajatkumar.beherafcs@kiit.ac.in",
                contact: "9886072882",
            },
            {
                position: "International Student Affairs (Academics)",
                name: "Dr. Jayanta Mondal",
                email: "jayanta.mondalfcs@kiit.ac.in",
                contact: "7908003806",
            },
            {
                position: "International Student Affairs (Academics)",
                name: "Dr. Mainak Bandyopadhyay",
                email: "mainak.bandyopadhyayfcs@kiit.ac.in",
                contact: "8009387402",
            },
            {
                position: "Time Table Governance",
                name: "Dr. Ajay Kumar Jena",
                email: "ajay.jenafcs@kiit.ac.in",
                contact: "9437232068",
            },
            {
                position: "Time Table Governance",
                name: "Dr. Abhaya Kumar Sahoo",
                email: "abhaya.sahoofcs@kiit.ac.in",
                contact: "9861443456",
            },
            {
                position: "Time Table Governance",
                name: "Dr. Dayal Kumar Behera",
                email: "dayal.beherafcs@kiit.ac.in",
                contact: "9853334495",
            },
            {
                position: "Guest Lecture Engagement",
                name: "Dr. Arghya Kundu",
                email: "arghya.kundufcs@kiit.ac.in",
                contact: "8792739730",
            },
            {
                position: "Guest Lecture Engagement",
                name: "Dr. Pradeep Kumar Mallick",
                email: "pradeep.mallickfcs@kiit.ac.in",
                contact: "8895885152",
            },
            {
                position: "Industry & Institute Collaboration",
                name: "Dr. Vikas Hassija",
                email: "vikas.hassijafcs@kiit.ac.in",
                contact: "8700580723",
            },
            {
                position: "Industry & Institute Collaboration",
                name: "Dr. Satyananda Champati Rai",
                email: "satya.raifcs@kiit.ac.in",
                contact: "9078513157",
            },
            {
                position: "Project Co-ordinator (UG)",
                name: "Dr. Jagannath Singh",
                email: "jagannath.singhfcs@kiit.ac.in",
                contact: "9861085883",
            },
            {
                position: "Project Co-ordinator (UG)",
                name: "Dr. Sushruta Mishra",
                email: "sushruta.mishrafcs@kiit.ac.in",
                contact: "7751995740",
            },
            {
                position: "Project Co-ordinator (UG)",
                name: "Dr. Saikat Chakraborty",
                email: "saikat.chakrabortyfcs@kiit.ac.in",
                contact: "993768429",
            },
        ],
        faculty: [
            {
                name: "A Ranjith",
                email: "a.ranjithfcs@kiit.ac.in",
            },
            {
                name: "Abhaya Kumar Sahoo",
                email: "abhaya.sahoofcs@kiit.ac.in",
            },
            {
                name: "Abhijit Deuri",
                email: "abhijit.deurifcs@kiit.ac.in",
            },
            {
                name: "Abhishek Raj",
                email: "abhishek.rajfcs@kiit.ac.in",
            },
            {
                name: "Abhishek Ray",
                email: "arayfcs@kiit.ac.in",
            },
            {
                name: "Abinas Panda",
                email: "abinas.pandafcs@kiit.ac.in",
            },
            {
                name: "Abir Sen",
                email: "abir.senfcs@kiit.ac.in",
            },
            {
                name: "Adyasha Dash",
                email: "adyasha.dashfcs@kiit.ac.in",
            },
            {
                name: "Ajay Anand",
                email: "ajay.anandfcs@kiit.ac.in",
            },
            {
                name: "Ajay Kumar Jena",
                email: "ajay.jenafcs@kiit.ac.in",
            },
            {
                name: "Ajaya Kumar Parida",
                email: "ajaya.paridafcs@kiit.ac.in",
            },
            {
                name: "Ajit Kumar Pasayat",
                email: "ajit.pasayatfcs@kiit.ac.in",
            },
            {
                name: "Aleena Swetapadma",
                email: "aleena.swetapadmafcs@kiit.ac.in",
            },
            {
                name: "Alok Kumar Jagadev",
                email: "alok.jagadevfcs@kiit.ac.in",
            },
            {
                name: "Ambika Prasad Mishra",
                email: "ambikaprasad.mishrafcs@kiit.ac.in",
            },
            {
                name: "Amiya Kumar Dash",
                email: "amiya.dasfcs@kiit.ac.in",
            },
            {
                name: "Amiya Ranjan Panda",
                email: "amiya.pandafcs@kiit.ac.in",
            },
            {
                name: "Amulya Ratna Swain",
                email: "amulyafcs@kiit.ac.in",
            },
            {
                name: "Anil Kumar Swain",
                email: "",
            },
            {
                name: "Anjan Bandyopadhyay",
                email: "anjan.bandyopadhyayfcs@kiit.ac.in",
            },
            {
                name: "Ankit Raj",
                email: "ankit.rajfcs@kiit.ac.in",
            },
            {
                name: "Anuja Kumar Acharya",
                email: "anujafcs@kiit.ac.in",
            },
            {
                name: "Aradhana Behura",
                email: "aradhana.behurafcs@kiit.ac.in",
            },
            {
                name: "Arup Abhinna Acharya",
                email: "aacharyafcs@kiit.ac.in",
            },
            {
                name: "Arup Sarkar",
                email: "arup.sarkarfcs@kiit.ac.in",
            },
            {
                name: "Ashish Singh",
                email: "ashish.singhfcs@kiit.ac.in",
            },
            {
                name: "Asif Uddin Khan",
                email: "asif.khanfcs@kiit.ac.in",
            },
            {
                name: "Banchhanidhi Dash",
                email: "banchhanidhi.dashfcs@kiit.ac.in",
            },
            {
                name: "Benazir Neha",
                email: "benazir.nehafcs@kiit.ac.in",
            },
            {
                name: "Bhabani Shankar Prasad Mishra",
                email: "bsmishrafcs@kiit.ac.in",
            },
            {
                name: "Bhaswati Sahoo",
                email: "bhaswati.sahoofcs@kiit.ac.in",
            },
            {
                name: "Bijoy Das",
                email: "bijoy.dasfcs@kiit.ac.in",
            },
            {
                name: "Bindu Agarwalla",
                email: "bindu.agarwalfcs@kiit.ac.in",
            },
            {
                name: "Biswajeet Sethi",
                email: "biswajeet.sethifcs@kiit.ac.in",
            },
            {
                name: "Biswajit Sahoo",
                email: "bsahoofcs@kiit.ac.in",
            },
            {
                name: "Chandani Kumari",
                email: "chandani.kumarifcs@kiit.ac.in",
            },
            {
                name: "Chittaranjan Pradhan",
                email: "chittaranjanfcs@kiit.ac.in",
            },
            {
                name: "Dayal Kumar Behera",
                email: "dayal.beherafcs@kiit.ac.in",
            },
            {
                name: "Debachudamani Prusti",
                email: "debachudamani.prustifcs@kiit.ac.in",
            },
            {
                name: "Debanjan Pathak",
                email: "debanjan.pathakfcs@kiit.ac.in",
            },
            {
                name: "Debashis Hati",
                email: "dhatifcs@kiit.ac.in",
            },
            {
                name: "Deependra Singh",
                email: "deependra.singhfcs@kiit.ac.in",
            },
            {
                name: "Dipti Dash",
                email: "dipti.dashfcs@kiit.ac.in",
            },
            {
                name: "G B Mund",
                email: "mund@kiit.ac.in",
            },
            {
                name: "Gananath Bhuyan",
                email: "gananatha.bhuyanfcs@kiit.ac.in",
            },
            {
                name: "Harish Kumar Patnaik",
                email: "hpatnaikfcs@kiit.ac.in",
            },
            {
                name: "Himansu Das",
                email: "himanshufcs@kiit.ac.in",
            },
            {
                name: "Hitesh Mohapatra",
                email: "hiteshmahapatra.fcs@kiit.ac.in",
            },
            {
                name: "Hrudaya Kumar Tripathy",
                email: "hktripathyfcs@kiit.ac.in",
            },
            {
                name: "Ipsita Paul",
                email: "ipsita.paulfcs@kiit.ac.in",
            },
        ],
    },
    {
        department: "Electrical Engineering",
        contactPersons: [],
        faculty: [
            {
                name: "Alivarani Mohapatra",
                email: "amohapatrafel@kiit.ac.in",
            },
            {
                name: "Ankit Kumar Soni",
                email: "ankit.sonifel@kiit.ac.in",
            },
            {
                name: "Arjyadhara Pradhan",
                email: "arjyadhara.pradhanfel@kiit.ac.in",
            },
            {
                name: "Babita Panda",
                email: "babitapfel@kiit.ac.in",
            },
            {
                name: "Banishree Misra",
                email: "bmisrafel@kiit.ac.in",
            },
            {
                name: "Byamakesh Nayak",
                email: "bnayakfel@kiit.ac.in",
            },
            {
                name: "Chinmoy Kumar Panigrahi",
                email: "chinmoy.panigrahifel@kiit.ac.in",
            },
            {
                name: "Chitralekha Jena",
                email: "chitralekha.jenafel@kiit.ac.in",
            },
            {
                name: "Deepak Kumar Gupta",
                email: "deepak.guptafel@kiit.ac.in",
            },
            {
                name: "Geetanjali Dei",
                email: "geetanjali.deifel@kiit.ac.in",
            },
            {
                name: "K.V.V.S.R. Chowdary",
                email: "rchowdaryfel@kiit.ac.in",
            },
            {
                name: "Lipika Nanda",
                email: "lnandafel@kiit.ac.in",
            },
            {
                name: "Lipsa Subhadarshini",
                email: "lipsa.subhadarshinifel@kiit.ac.in",
            },
            {
                name: "Manoj K. Maharana",
                email: "mkmfel@kiit.ac.in",
            },
            {
                name: "Padarbinda Samal",
                email: "padarbinda.samalfel@kiit.ac.in",
            },
            {
                name: "Pampa Sinha",
                email: "pampa.sinhafel@kiit.ac.in",
            },
            {
                name: "Pradeep Kumar Sahu",
                email: "pradeep.sahufel@kiit.ac.in",
            },
            {
                name: "Ranjeeta Patel",
                email: "ranjeeta.patelfel@kiit.ac.in",
            },
            {
                name: "Roshan Nayak",
                email: "roshan.nayakfel@kiit.ac.in",
            },
            {
                name: "Rudra Narayan Dash",
                email: "rudra.dashfel@kiit.ac.in",
            },
            {
                name: "Rudranarayan Senapati",
                email: "rsenapatifel@kiit.ac.in",
            },
            {
                name: "Samita Rani Pani",
                email: "samita.panifel@kiit.ac.in",
            },
            {
                name: "Sanhita Mishra",
                email: "sanhita.mishrafel@kiit.ac.in",
            },
            {
                name: "Sarat Chandra Swain",
                email: "scswainfel@kiit.ac.in",
            },
            {
                name: "Sarita Samal",
                email: "ssamalfel@kiit.ac.in",
            },
            {
                name: "Satyabrata Sahoo",
                email: "satyabrata.sahoofel@kiit.ac.in",
            },
            {
                name: "Satyaranjan Jena",
                email: "snjenafel@kiit.ac.in",
            },
            {
                name: "Shubhasri Kundu",
                email: "shubhasri.kundufel@kiit.ac.in",
            },
            {
                name: "Snehalika",
                email: "snehalika.fel@kiit.ac.in",
            },
            {
                name: "Soubhagya Ranjan Prusty",
                email: "soubhagya.prustyfel@kiit.ac.in",
            },
            {
                name: "Srikanta Mohapatra",
                email: "srikantfel@kiit.ac.in",
            },
            {
                name: "Sriparna Roy Ghatak",
                email: "sghatakfel@kiit.ac.in",
            },
            {
                name: "Subhra Debdas",
                email: "subhra.debdasfel@kiit.ac.in",
            },
            {
                name: "Subodh Kumar Mohanty",
                email: "subodh.mohantyfel@kiit.ac.in",
            },
            {
                name: "Subrat Behera",
                email: "sbeherafel@kiit.ac.in",
            },
            {
                name: "Subrat Kumar Barik",
                email: "skbarikfel@kiit.ac.in",
            },
            {
                name: "Suchismita Roy",
                email: "sroyfel@kiit.ac.in",
            },
            {
                name: "Swagat Das",
                email: "swagat.dasfel@kiit.ac.in",
            },
            {
                name: "Tapaswini Biswal",
                email: "tapaswini.biswalfel@kiit.ac.in",
            },
            {
                name: "Vikash Anand",
                email: "vikash.anandfel@kiit.ac.in",
            },
        ],
    },
    {
        department: "Electronics Engineering",
        contactPersons: [],
        faculty: [
            { name: "Abhik Gorai", email: "abhik.goraifet@kiit.ac.in" },
            { name: "Abu Nasar Ghazali", email: "abu.ghazalifet@kiit.ac.in" },
            { name: "Akshaya Kumar Pati", email: "akshaya.patifet@kiit.ac.in" },
            { name: "Amit Bakshi", email: "amitfet@kiit.ac.in" },
            { name: "Amitkumar V. Jha", email: "amit.jhafet@kiit.ac.in" },
            { name: "Amlan Datta", email: "amlanfet@kiit.ac.in" },
            { name: "Amrit Mukherjee", email: "" },
            { name: "Ankit Kudeshia", email: "" },
            { name: "Ansuman Patnaik", email: "ansumanfet@kiit.ac.in" },
            { name: "Anupam Samui", email: "asamuifet@kiit.ac.in" },
            { name: "Anupama Senapati", email: "anupamafet@kiit.ac.in" },
            { name: "Arighna Deb", email: "airghna.debfet@kiit.ac.in" },
            { name: "Arindam Basak", email: "abasakfet@kiit.ac.in" },
            { name: "Arun Kumar Ray", email: "akrayfet@kiit.ac.in" },
            { name: "Aryadhara Pradhan", email: "" },
            { name: "Ayaskanta Mishra", email: "ayaskanta.mishrafet@kiit.ac.in" },
            { name: "B Shivalal Patro", email: "bspatrofet@kiit.ac.in" },
            { name: "Bhargav Appasani", email: "bhargav.appasanifet@kiit.ac.in" },
            { name: "Bikash Kumar Behera", email: "bikash.beherafet@kiit.ac.in" },
            { name: "Bishnu Prasad De", email: "bishnu.defet@kiit.ac.in" },
            { name: "Budhadeb Maity", email: "bmaityfet@kiit.ac.in" },
            { name: "Deep Mukherjee", email: "deepmukherjeefet@kiit.ac.in" },
            { name: "Deepak Kumar Rout", email: "deepak.routfet@kiit.ac.in" },
            { name: "Mano Ranjan Kumar", email: "mano.kumarfet@kiit.ac.in" },
            { name: "S. K. Mohapatra", email: "sushanta.mohapatrafet@kiit.ac.in" },
            { name: "Ganaraj P S", email: "ganaraj.psfet@kiit.ac.in" },
            { name: "Israj Ali", email: "israjfet@kiit.ac.in" },
            { name: "Jabir Hussain", email: "jabir.hussainfet@kiit.ac.in" },
            { name: "Jibendu Sekhar Roy", email: "drjsroy@kiit.ac.in" },
            { name: "Jitendra Kumar Das", email: "jkdasfet@kiit.ac.in" },
            { name: "Joy Choudhary", email: "" },
            { name: "Jyoti Ranjan Panda", email: "jyotiranjan.pandafet@kiit.ac.in" },
        ],
    },
    {
        department: "Civil Engineering",
        contactPersons: [],
        faculty: [
            { name: "Amit Kumar Das", email: "amit.dasfce@kiit.ac.in" },
            { name: "Aparupa Pani", email: "aparupa.panifce@kiit.ac.in" },
            { name: "Asish Kumar Pani", email: "apanifce@kiit.ac.in" },
            { name: "Bandita Paikaray", email: "bandita.paikarayfce@kiit.ac.in" },
            { name: "Benu Gopal Mohapatra", email: "director.civil@kiit.ac.in" },
            { name: "Bitanjaya Das", email: "bdasfce@kiit.ac.in" },
            { name: "Brundaban Beriha", email: "brundaban.berihafce@kiit.ac.in" },
            { name: "Chinmay Kumar Kundu", email: "chinmay.kundufce@kiit.ac.in" },
            { name: "Dillip Kumar Bera", email: "dberafce@kiit.ac.in" },
            { name: "Dipti Ranjan Biswal", email: "dipti.biswalfce@kiit.ac.in" },
            { name: "Gaurav Udgata", email: "gaurav.udgatafce@kiit.ac.in" },
            { name: "Himanshu Sekhar", email: "" },
            { name: "Ipsita Mohanty", email: "ipsita.mohantyfce@kiit.ac.in" },
            { name: "Ipsita Panda", email: "ipsita.pandafce@kiit.ac.in" },
            { name: "Jyotiprakash Padhi", email: "jyotiprakash.padhifce@kiit.ac.in" },
            { name: "Kalpana Sahoo", email: "kalpana.sahoofce@kiit.ac.in" },
            { name: "Kirtikanta Sahoo", email: "kirtikanta.sahoofce@kiit.ac.in" },
            {
                name: "Kshyana Prava Samal",
                email: "kshyanaprava.samalfce@kiit.ac.in",
            },
            { name: "Kundan Samal", email: "kundan.samalfce@kiit.ac.in" },
            {
                name: "Madhu Lisha Pattanaik",
                email: "madhulisha.pattanaikfce@kiit.ac.in",
            },
            { name: "Malaya Mohanty", email: "malaya.mohantyfce@kiit.ac.in" },
            { name: "Manas Mishra", email: "" },
            { name: "Mohibullah", email: "mohibullah.fce@kiit.ac.in" },
            {
                name: "Mojahedul Islam Nayyer",
                email: "mojahedul.nayyerfce@kiit.ac.in",
            },
            { name: "Narayan Chandra Moharana", email: "nmoharanafce@kiit.ac.in" },
            { name: "Nazia Tazin Imran", email: "nazia.imranfce@kiit.ac.in" },
            {
                name: "Paromita Chakraborty",
                email: "paromita.chakrabortyfce@kiit.ac.in",
            },
            {
                name: "Prasanna Kumar Acharya",
                email: "prasanna.acharyafce@kiit.ac.in",
            },
            { name: "Preetynanda Nanda", email: "preety.nandafce@kiit.ac.in" },
            { name: "Sanjib Moulick", email: "smoulickfce@kiit.ac.in" },
            { name: "Purnachandra Saha", email: "purnasahafce@kiit.ac.in" },
            { name: "Rachita Panda", email: "rachita.pandafce@kiit.ac.in" },
            { name: "Rana Chattaraj", email: "rana.chattarajfce@kiit.ac.in" },
            { name: "Satya Ranjan Samal", email: "satya.samalfce@kiit.ac.in" },
            { name: "Satyajeet Nanda", email: "satyajeet.nandafce@kiit.ac.in" },
            { name: "Sunny Jaiswal", email: "sunny.jaiswalfce@kiit.ac.in" },
            { name: "Tribikram Mohanty", email: "tmohantyfce@kiit.ac.in" },
        ],
    },
    {
        department: "Mechanical Engineering",
        contactPersons: [],
        faculty: [
            { name: "Abhilas Swain", email: "abhilas.swainfme@kiit.ac.in" },
            { name: "Ajay Kumar Behera", email: "ajay.beherafme@kiit.ac.in" },
            { name: "Akshaya Kumar Rout", email: "akroutfme@kiit.ac.in" },
            { name: "Ambesh Kumar", email: "ambesh.kumarfme@kiit.ac.in" },
            { name: "Amlana Panda", email: "amlana.pandafme@kiit.ac.in" },
            { name: "Anil Kumar Rout", email: "anilfme@kiit.ac.in" },
            { name: "Anish Pandey", email: "anish.pandeyfme@kiit.ac.in" },
            { name: "Ashok Kumar Sahoo", email: "asahoofme@kiit.ac.in" },
            { name: "Asit Behera", email: "asit.beherafme@kiit.ac.in" },
            { name: "B. Surekha", email: "surekhafme@kiit.ac.in" },
            { name: "Basanta Kumar Nanda", email: "bnandafme@kiiit.ac.in" },
            { name: "Basanta Kumar Rana", email: "basanta.ranafme@kiit.ac.in" },
            { name: "Bharat Chandra Routara", email: "broutrafme@kiit.ac.in" },
            { name: "Bijaya Bijeta Nayak", email: "bijaya.nayakfme@kiit.ac.in" },
            { name: "Debjyoti Sahu", email: "debjyoti.sahufme@kiit.ac.in" },
            { name: "Deepak Singhal", email: "deepak.singhalfme@kiit.ac.in" },
            { name: "Smitirupa Pradhan", email: "smitirupa.pradhanfme@kiit.ac.in" },
            { name: "Gyan Sagar Sinha", email: "gyan.sinhafme@kiit.ac.in" },
            { name: "Hemalata Jena", email: "hemalata.jenafme@kiit.ac.in" },
            { name: "Isham Panigrahi", email: "ipanigrahifme@kiit.ac.in" },
            { name: "Jitendra Kumar Patel", email: "jitendra.patelfme@kiit.ac.in" },
            { name: "Kalyani Mohanta", email: "kalyani.mohantafme@kiit.ac.in" },
            { name: "Kamal Kishore Joshi", email: "kamal.joshifme@kiit.ac.in" },
            { name: "Kunja Bihari Sahu", email: "kbsahufme@kiit.ac.in" },
            { name: "Madhumita Mohanty", email: "madhumita.mohanty@kiit.ac.in" },
            {
                name: "Mantra Prasad Satpathy",
                email: "mantra.satpathyfme@kiit.ac.in",
            },
            { name: "Md Ehtesham Hasan", email: "mdehtesham.hasanfme@kiit.ac.in" },
            { name: "Mrutyunjay Jena", email: "mrutyunjaya.jenafme@kiit.ac.in" },
            { name: "Nitin Sharma", email: "nitin.sharmafme@kiit.ac.in" },
            { name: "Purna Chandra Mishra", email: "pcmishrafme@kiit.ac.in" },
            { name: "Pushkar Jha", email: "pushkar.jhafme@kiit.ac.in" },
            { name: "Radha Kanta Sarangi", email: "radha.sarangifme@kiit.ac.in" },
            { name: "Rita Kumari Sahu", email: "ritasahufme@kiit.ac.in" },
            { name: "Ruby Mishra", email: "rubymishrafme@kiit.ac.in" },
            { name: "Swarup Kumar Nayak", email: "swarup.nayakfme@kiit.ac.in" },
            { name: "Vijay Kumar Mishra", email: "vijay.mishrafme@kiit.ac.in" },
        ],
    },
];

export default facultyList;
